// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Prisma config is optional for this project setup in the demo.
// Export a noop default to avoid build-time errors when prisma is not installed.
export default {} as const;
