-- SiteHub: sites and companies columns for API compatibility

-- Sites: columns expected by /api/sites
ALTER TABLE sites ADD COLUMN IF NOT EXISTS location JSONB;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS geofence JSONB;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS latitude NUMERIC;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS longitude NUMERIC;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS radius_meters NUMERIC;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS show_on_map BOOLEAN DEFAULT TRUE;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS manager_id UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS rams_version TEXT;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS ramsversion TEXT;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE sites ADD COLUMN IF NOT EXISTS company_id TEXT;

-- Companies: ensure updated_at
ALTER TABLE companies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
